global:
  smtp_smarthost: 'localhost:587'
  smtp_from: 'alertmanager@company.com'

route:
  group_by: ['alertname', 'cluster', 'service']
  group_wait: 10s
  group_interval: 10s
  repeat_interval: 1h
  receiver: 'webhook-notifications'
  routes:
  - match:
      severity: critical
    receiver: 'critical-webhook'
  - match:
      severity: warning
    receiver: 'warning-webhook'

receivers:
- name: 'webhook-notifications'
  webhook_configs:
  - url: 'http://webhook-handler:8080/webhook'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'admin'
        password: 'secret'

- name: 'critical-webhook'
  webhook_configs:
  - url: 'http://webhook-handler:8080/webhook/critical'
    send_resolved: true
    http_config:
      basic_auth:
        username: 'admin'
        password: 'secret'

- name: 'warning-webhook'
  webhook_configs:
  - url: 'http://webhook-handler:8080/webhook/warning'
    send_resolved: true

inhibit_rules:
  - source_match:
      severity: 'critical'
    target_match:
      severity: 'warning'
    equal: ['alertname', 'cluster', 'service']