---
- name: Restart NGINX Service
  hosts: localhost
  gather_facts: no
  vars:
    ansible_python_interpreter: /usr/local/bin/python3
    container_name: "nginx"
    service_name: "nginx"
    
  tasks:
    - name: Log alert information
      debug:
        msg: |
          Alert: {{ alert_name | default('Unknown') }}
          Severity: {{ severity | default('Unknown') }}
          Service: {{ service | default('Unknown') }}
          Timestamp: {{ timestamp | default('Unknown') }}

    - name: Check if NGINX container is running
      community.docker.docker_container_info:
        name: "{{ container_name }}"
      register: container_info
      ignore_errors: yes

    - name: Display container status
      debug:
        msg: "Container {{ container_name }} status: {{ container_info.container.State.Status if container_info.exists else 'Not found' }}"

    - name: Restart NGINX container if it exists
      community.docker.docker_container:
        name: "{{ container_name }}"
        state: started
        restart: true
        restart_policy: unless-stopped
      when: container_info.exists | default(false)

    - name: Start NGINX container if it doesn't exist
      community.docker.docker_container:
        name: "{{ container_name }}"
        image: nginx:alpine
        state: started
        restart_policy: unless-stopped
        ports:
          - "80:80"
        networks:
          - name: monitoring
      when: not container_info.exists | default(false)

    - name: Wait for NGINX to be ready
      uri:
        url: "http://nginx:80"
        method: GET
        status_code: [200, 403]  # 403 is acceptable for default nginx
      retries: 10
      delay: 3
      register: nginx_health_check
      until: nginx_health_check.status in [200, 403]

    - name: Log recovery success
      debug:
        msg: "NGINX service recovery completed successfully at {{ ansible_date_time.iso8601 }}"

    - name: Send recovery notification
      uri:
        url: "http://alertmanager:9093/-/reload"
        method: POST
      ignore_errors: yes

    - name: Create recovery log entry
      lineinfile:
        path: /tmp/recovery.log
        create: yes
        line: "{{ ansible_date_time.iso8601 }} - NGINX service restarted successfully - Alert: {{ alert_name | default('Manual') }}"
      delegate_to: localhost
